### ISSUE TITLE
[Request] Downloading not just the base files, but the whole game

### ISSUE THREAD

**Issue by Wowhungarian** [The-Cataclysm-Preservation-Project/ClientDownloader#1]
Hi all!

I would like to build up a Cata server, but I'm struggling with getting the right client, which is good enough for the vmap exactor of the Preservation Project. Is it possible to extend the ClientDownloader with a function, that downloads the full 4.3.4 client?

**Comment by Wowhungarian** [comment]
Btw, shomehow the WoW.mfil file changes, when I start WoW.exe.

**Comment by funjoker** [comment]
[I need a full client](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/wiki/Information#i-need-a-full-client)

Check it out.
The ClientDownloader only downloads data of the main wow folder (.exe, .dll, .mfil).
The Data folder is downloaded with the [WoWRegeneration](https://github.com/The-Cataclysm-Preservation-Project/wowregeneration).

The .mfil file is changed because:
- You didn't patch the client.
- You didn't change the patchlist part inside Config.wtf in WTF folder
  `SET patchlist`

**Comment by Wowhungarian** [comment]
Woow, thanks for the detailed explanation. I close this. :)
